#! /bin/sh
cd models
echo "downloading google's pretrained word embeddings..."                
curl -O https://s3.amazonaws.com/dl4j-distribution/GoogleNews-vectors-negative300.bin.gz
gzip -d GoogleNews-vectors-negative300.bin.gz
