#!/bin/sh
virtualenv env
echo "created virtual environment"
source env/bin/activate
echo "installing required dependencies may take some time..."
pip install -r requirements.txt
echo "requirements installed, creating jupyter kernel"
ipython kernel install --name "Python3_marble" --user
echo "created kernel called 'Python3_marble'"
echo "downloading nltk stopwords..."
python download_nlt_stopwords.py
